name: timelanes
description: "A Widget to show visual events on a horizontal timeline"
version: 0.9.0
homepage: https://noclevercode.com/timelanes

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  test: ^1.24.0
